-- Migration: Add comprehensive profile fields for enhanced LinkedIn data
-- This migration adds fields to store detailed career information for better AI matching

-- Add comprehensive professional fields
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS experience_summary TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS all_roles TEXT[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS all_companies TEXT[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS education_summary TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS years_of_experience INTEGER;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS certifications TEXT[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS key_achievements TEXT[] DEFAULT '{}';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS expertise_areas TEXT[] DEFAULT '{}';

-- Add comprehensive vectorization text field for semantic search
-- This field contains ALL profile information in a text format for embedding generation
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vectorization_text TEXT;

-- Create indexes for new array fields to enable fast filtering
CREATE INDEX IF NOT EXISTS idx_profiles_all_roles ON profiles USING GIN(all_roles);
CREATE INDEX IF NOT EXISTS idx_profiles_all_companies ON profiles USING GIN(all_companies);
CREATE INDEX IF NOT EXISTS idx_profiles_expertise_areas ON profiles USING GIN(expertise_areas);
CREATE INDEX IF NOT EXISTS idx_profiles_certifications ON profiles USING GIN(certifications);

-- Add comment for documentation
COMMENT ON COLUMN profiles.vectorization_text IS 'Comprehensive text combining all profile fields for semantic search embedding. Generated by AI extraction from LinkedIn data.';
COMMENT ON COLUMN profiles.experience_summary IS 'AI-generated summary of career trajectory and key achievements';
COMMENT ON COLUMN profiles.all_roles IS 'All job titles held throughout career';
COMMENT ON COLUMN profiles.all_companies IS 'All companies worked at throughout career';
COMMENT ON COLUMN profiles.expertise_areas IS 'Core areas of professional expertise (5-10 areas)';
COMMENT ON COLUMN profiles.key_achievements IS 'Notable achievements extracted from experience';
